### ISSUE TITLE
Add learning material

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Documentation#12]
@Mastercuber would like to have some tutorials about topics like "Git for beginners" and "Advanced Git usage". So let's find an appropriate place and put [our tutorials](https://www.youtube.com/playlist?list=PL1CiawkXA01MFZ_ieeZvEL_g2jsYLFSsB) on the documentation site. 

See:
https://github.com/Human-Connection/Human-Connection/issues/40
https://github.com/Human-Connection/Human-Connection/issues/41

**Comment by Lulalaby** [comment]
I'll do it <3
