### ISSUE TITLE
graphical overview of the server api is missing

### ISSUE THREAD

**Issue by frankgerhardt** [Human-Connection/Documentation#2]
At https://docs.human-connection.org/server-api/overview.html no diagram is shown.

**Comment by Lulalaby** [comment]
Where are the diagrams?

**Comment by Lulalaby** [comment]
@appinteractive

**Comment by appinteractive** [comment]
Okay, I can see that the image embeds got lost in the process. 
https://github.com/Human-Connection/Documentation/commit/112fd737492f4c13b0a1d514dd414f77420f7104

**Comment by Lulalaby** [comment]
Added missing files again and added to pages.
