### ISSUE TITLE
Describe what a foreign user is

### ISSUE THREAD

**Issue by frankgerhardt** [Human-Connection/Documentation#3]
In the REST API there is this GET:
```
GET Is user following foreign user?
http://localhost:3030/follows?userId=5ac32aef65a9c2125784a455&foreignId=5ac32b0465a9c2125784a459&foreignService=users&$limit=0
```
What is a foreign user? 

Add this information to the docs, even better describe the concepts used by HC.

**Comment by Lulalaby** [comment]
@appinteractive 😸  nicht vergessen

**Comment by appinteractive** [comment]
The `foreignUser` is a user or organization that the `user` follows. 

@Lulalaby could you please add that phrase to the docs with a hint for more information to follow? I’m just on mobile right now and before I forget it again... 😅 many things for poking me on that issue.
